Ext.define 'Vcare.view.shipment.Split',
    extend: 'Ext.window.Window'
    alias: 'widget.wg-shipment-split'
    modal: yes
    initComponent: ->

        @items = []
        data = @config.data
        @items.push({
            xtype: 'grid'
            region : 'center'
            title : 'Shipment Units'
            width: 400
            bodyPadding: 10
            reference: 'refShipmentUnitList'
            store: Ext.create 'Ext.data.Store',
                data: data.data.units
                fields: [
                    'id'
                ]

            columns : [
                text: 'ID'
                dataIndex: 'id'
            ]
            selType: 'checkboxmodel'

            tbar:
                items: [
                    disabled: no
                    text: 'Split the selected items'
                    iconCls:'pencil-square-o '
                    handler: 'onSplit'
                ]

        })


        @callParent(arguments)
        @center()
# ---
# generated by js2coffee 2.1.0
