parameters:
    app.http_client.base_url: 'http://127.0.0.1:8000/app_dev.php/'
    app.http_client.api_url: 'http://127.0.0.1:8000/app_dev.php/api/'
    app.http_client.token_url: 'oauth/v2/token'

    app.client.id: 1oacj6ctnl8kg8kw4g0048wgkcws0c888cgck0g8844cs8oggo
    app.client.secret: 5qswyupaj78ccwwks40cc0o8soo88ko4scwc0wo0owwcwo0ook
    app.client.username: admin
    app.client.password: admin0hk

    app.uri_map:
        product-variants: 'products/{productId}/variants'
        taxons: 'taxonomies/{taxonomyId}/taxons'
        items: 'orders/{orderId}/items'
        coupons: 'promotions/{promotionId}/coupons'
        provinces: 'countries/{countryId}/provinces'

services:
    app.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ "@database_connection" ]

    # Http client that is used to obtain OAuth2 token
    app.http_client_oauth:
        class: GuzzleHttp\Client
        arguments:
            - { base_url: %app.http_client.base_url% }

    # Password credentials that use http client to authenticate user with given data
    app.oauth2.grant_type.password_credentials:
        class: CommerceGuys\Guzzle\Oauth2\GrantType\PasswordCredentials
        arguments:
            - "@app.http_client_oauth"
            - { token_url: %app.http_client.token_url%, client_id: %app.client.id%, client_secret: %app.client.secret%, username: %app.client.username%, password: %app.client.password% }

    # Refresh token that use http client to refresh oauth2 token
    app.oauth2.grant_type.refresh_token:
        class: CommerceGuys\Guzzle\Oauth2\GrantType\RefreshToken
        arguments:
            - "@app.http_client_oauth"
            - { token_url: %app.http_client.token_url%, client_id: %app.client.id%, client_secret: %app.client.secret%, username: %app.client.username%, password: %app.client.password% }

    # Subscriber used by Sylius API Client to provide OAuth2 authentication
    app.oauth2.subscriber.api:
        class: CommerceGuys\Guzzle\Oauth2\Oauth2Subscriber
        arguments: ["@app.oauth2.grant_type.password_credentials", "@app.oauth2.grant_type.refresh_token"]

    # Http client that is used to connect with Sylius API
    app.http_client_api:
        class: GuzzleHttp\Client
        arguments:
            - { base_url: '%app.http_client.api_url%', defaults: { auth: 'oauth2', subscribers: ["@app.oauth2.subscriber.api"] } }

    # Sylius API Client
    app.api_client:
        class: Sylius\Api\Client
        arguments: ["@app.http_client_api"]

    # Uri map with custom uris
    app.api_resolver.uri_map:
        class: Sylius\Api\Map\ArrayUriMap
        arguments: [ %app.uri_map% ]

    # Initialize Api resolver with uri map
    app.api_resolver:
        class: Sylius\Api\ApiResolver
        arguments: ["@app.api_client", "@app.api_resolver.uri_map"]
