parameters:
    api_configs:
        clientId: "%api.client.id%"
        clientSecret: "%api.client.secret%"
        redirectUri: "%api.client.url_redirect%"
        urlAuthorize: "%api.client.url_authorize%"
        urlAccessToken: "%api.client.url_token%"
        urlResourceOwnerDetails: "%api.client.url_owner%"

services:
    guzzle.stack:
        public: false
        class: GuzzleHttp\HandlerStack
        factory: [ GuzzleHttp\HandlerStack, create ]
        calls:
            - [ push, [ "@guzzle.logger" ] ]

    guzzle.message_formatter:
        public: false
        class: GuzzleHttp\MessageFormatter

    guzzle.logger:
        public: false
        class: callback
        arguments: ["@logger", "@guzzle.message_formatter"]
        factory: [GuzzleHttp\Middleware, log]

    guzzle.http_client:
        class: GuzzleHttp\Client
        arguments:
            -
                handler: "@guzzle.stack"
                base_uri: %api.client.url_base%
                headers:
                    auth: "oauth2"
                    exceptions: false
                    Accept: "application/json"
                    Content-Type: "application/json"
                    User-Agent: "DoSAPI/0.1"

    oauth2.provider:
        class: League\OAuth2\Client\Provider\GenericProvider
        arguments: [ "%api_configs%" ]

    api.client:
        class: AppBundle\OAuth\Client
        arguments:
            - "@guzzle.http_client"
            - "@guzzle.stack"
            - "@oauth2.provider"
            - "@security.token_storage"

    api.user_provider:
        class: AppBundle\Security\UserProvider
        arguments: [ "@oauth2.provider" ]

