Ext.define 'Vcare.view.payments.Show',
    extend: 'Ext.window.Window'
    alias: 'widget.wg-payments-show'
    modal: yes

    initComponent: ->
        @items = []
        data = @config.data

        @items.push({
            xtype: 'grid'
            region : 'center'
            title : 'Payments'
            width: 768
            scrollable: yes
            maxHeight: 768
            reference: 'refPaymentsList'
            store:
                type: 'store-payments'
                data: data.getPayments().data

            columns : [
                text: 'ID'
                dataIndex: 'id'
                width: 100
            ,
                text: 'Method'
                renderer: (v, m, r) ->
                    return r.getMethod().getName()
            ,
                text: 'State'
                dataIndex: 'state'
                flex: 1
            ,
                text: 'Amount'
                dataIndex: 'amount'
                flex: 1
                renderer: (v, m, r) ->
                    return r.getPrice(v)
            ,
                text: 'Currency'
                dataIndex: 'currency'
                flex: 1
            ,
                text: 'Paid at'
                dataIndex: 'created_at'
                width: 180
            ]
        })

        @callParent(arguments)
        @center()
# ---
# generated by js2coffee 2.1.0
